### ISSUE TITLE
whether it is still being  maintained

### ISSUE THREAD

**Issue by LJDong** [ysjiang4869/swagger2postman#1]
sorry, I hava the same problem that to update swagger api to postman

**Comment by ysjiang4869** [comment]
> sorry, I hava the same problem that to update swagger api to postman

Any problem? please paste your swagger response.

**Comment by LJDong** [comment]
`Error faking a schema. Not faking this schema. Schema: {
  type: 'object',
  properties: {
....
Error Error: unknown primitive "int32" in`

error like this, thank you

**Comment by ysjiang4869** [comment]
> `Error faking a schema. Not faking this schema. Schema: { type: 'object', properties: { .... Error Error: unknown primitive "int32" in`
> 
> error like this, thank you

Something special in your api, I can not reproduce the error. 
Please paste the specific swagger doc get from api such as `http://127.0.0.1:8085/v2/api-docs` response that cause the problem.
Feel free to hide your sensitive info

**Comment by ysjiang4869** [comment]
no futher information
