### ISSUE TITLE
Fails swaggerObj using openapi 3.0 because it's missing 2.0 requirements (workaround provided)

### ISSUE THREAD

**Issue by eristocrates** [ysjiang4869/swagger2postman#4]
**Describe the bug**
When running OpenAPI 3.0, the conditional `if (swaggerObj.swagger !== '2.0')` in helpers.js will cause an error. Pictured below is me commenting out that check and replacing it with the proper check for 3.0 specifications [provided here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#versions). I'm guessing you'd want to add a proper check for which openapi version the swaggerObj is instead of just hardcoding for 3.0 like I did.

**Environment**
- OS version: Windows 11
- postman version: v10.12.4
- nodejs version 14.0.0

![image](https://user-images.githubusercontent.com/42102473/226717788-a2d3c41a-6840-48cf-b6eb-92c28b139a90.png)

**Comment by ysjiang4869** [comment]
Fine, this tool was design to support swagger2.0.
As your need, I will add openapi 3.0 in next release.

**Comment by ysjiang4869** [comment]
Already support OpenAPI3 and have a try! referer #6
