### ISSUE TITLE
Documentation suggestions regarding installation failures for windows users and/or Node 18 users

### ISSUE THREAD

**Issue by eristocrates** [ysjiang4869/swagger2postman#5]
**Describe the bug**
Not exactly a bug, but I spent quite a bit of time dealing with problems and wanted to share solutions. 

**Environment**
- OS version: Windows 11
- postman version: v10.12.4
- initial nodejs version: 18.9.0

***npm install failure, npm ERR! code 1***
Initially, I was unable to `npm install` due to nodejieba refusing to install. Turns out Node versions above 16 fail to build nodejieba, so version 16 is needed. For windows, the solution was [installing nvm](https://github.com/coreybutler/nvm-windows) to manage multiple versions, but i believe the [linux solution is n](https://www.npmjs.com/package/n). To your credit, these are issues i had to dig through nodejieba's issue tracker to resolve, but I thought it wouldn't hurt to mention them on this project as well.

***In windows environment, properly setting POSTMAN_API_KEY and NODE_TLS_REJECT_UNAUTHORIZED***
This could have been my unfamiliarity with Powershell, but i initially tried setting an environment variable via windows settings not realizing i needed a process environment variable to be set. Even after solving that, i was getting rejected for a lack of authentication. To solve both, I suggest a simple powershell script. here's an example swagger2postman.ps1
```
$scriptBlock = {
	$Env:POSTMAN_API_KEY='<your api key here>'
	$Env:NODE_TLS_REJECT_UNAUTHORIZED='0'
	node index.js -s <your cli command. the default was test>
}
Invoke-Command -ScriptBlock $scriptBlock
```

**Comment by ysjiang4869** [comment]
Ok, thanks for your suggest. I got two things to be done:
- [ ]  Test nodejs version compatibility
- [x]  move environment varible to nodejs .env file to make set environment easy

**Comment by ysjiang4869** [comment]
Tested node18 is ok.
May be the problem only exist in Windows. I will try it latter.

**Comment by ysjiang4869** [comment]
fixed, nodejieba was not dependend in this project. Just remove it.
